name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Déploiement déclenché lors d'un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Clonage du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hostname and IP
        run: |
          echo ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}
          echo "Public IP: $(curl ifconfig.me)"

      # Étape 2 : Configurer l'agent SSH
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 3 : Déployer l'application via Docker Compose
      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            cd /path/to/your/project

            # Stopper les containers en cours d'exécution
            docker-compose down

            # Mettre à jour le code source
            git pull origin main

            # Rebuild et relancer les containers
            docker-compose up --build -d
          EOF
